# Generated by Django 5.1.2 on 2024-10-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_teammembermodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembermodel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teammembermodel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teammembermodel',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teammembermodel',
            name='first_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teammembermodel',
            name='first_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teammembermodel',
            name='first_name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teammembermodel',
            name='last_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teammembermodel',
            name='last_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teammembermodel',
            name='last_name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teammembermodel',
            name='role_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammembermodel',
            name='role_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammembermodel',
            name='role_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='first_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='first_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='first_name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='username',
            field=models.CharField(default='default_username', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
