# Generated by Django 5.1.2 on 2024-10-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teammembermodel_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='location',
            field=models.CharField(default='Tashkent, Uzbekistan', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='location_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='location_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='location_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='organization_name',
            field=models.CharField(default='Tashkent', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='organization_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='organization_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='organization_name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
