# Generated by Django 5.1.2 on 2024-10-10 13:11

import users.models
import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermodel_linkedin_url_usermodel_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='picture',
            field=models.ImageField(upload_to='users', validators=[users.models.validate_image_size]),
        ),
    ]
