# Generated by Django 5.1.2 on 2024-10-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usermodel_picture_alter_usermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembermodel',
            name='picture',
            field=models.ImageField(upload_to='team_pictures/'),
        ),
    ]
