# Generated by Django 5.1.2 on 2024-10-11 09:59

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_teammembermodel_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='first_name_ru',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='first_name_uz',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_name_ru',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_name_uz',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='location_en',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='location_ru',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='location_uz',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='organization_name_en',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='organization_name_ru',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='organization_name_uz',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='picture',
            field=models.ImageField(blank=True, default='assets/images/avatar/default_avatar.png', null=True, upload_to='users', validators=[users.models.validate_image_size]),
        ),
    ]
