# Generated by Django 5.1.2 on 2024-10-11 10:38

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_usermodel_email_remove_usermodel_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='picture',
            field=models.ImageField(blank=True, default='default_avatar.png', null=True, upload_to='users', validators=[users.models.validate_image_size]),
        ),
    ]
