# Generated by Django 5.1.2 on 2024-10-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemmodel',
            options={'ordering': ['title'], 'verbose_name': 'Problem', 'verbose_name_plural': 'Problems'},
        ),
    ]
