# Generated by Django 5.1.2 on 2024-10-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_offer', '0003_faqmodel_answer_en_faqmodel_answer_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offermodel',
            name='picture',
        ),
        migrations.AddField(
            model_name='offermodel',
            name='views_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
